# Source: ping-devops/templates/pingdataconsole/workload.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingdataconsole
  name: likeminds-pingdataconsole
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: likeminds
      app.kubernetes.io/name: pingdataconsole
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: likeminds
        app.kubernetes.io/name: pingdataconsole
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: likeminds-global-env-vars
            optional: true
        - configMapRef:
            name: likeminds-env-vars
            optional: true
        - configMapRef:
            name: likeminds-pingdataconsole-env-vars
        - secretRef:
            name: devops-secret
            optional: true
        - secretRef:
            name: likeminds-pingdataconsole-git-secret
            optional: true
        image: pingidentity/pingdataconsole:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /opt/liveness.sh
          failureThreshold: 4
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: pingdataconsole
        ports:
        - containerPort: 8443
          name: https
        readinessProbe:
          exec:
            command:
            - /opt/readiness.sh
          failureThreshold: 4
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 0
            memory: .5Gi
        startupProbe:
          exec:
            command:
            - /opt/liveness.sh
          failureThreshold: 90
          periodSeconds: 10
          timeoutSeconds: 5
      enableServiceLinks: true
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 9031