apiVersion: v1
kind: Service
metadata:
  annotations:
    #External for Public Loadbalancer | Internal for Internal Loadbalancer
    networking.gke.io/load-balancer-type: "External"
    # networking.gke.io/load-balancer-type: "Internal"
  labels:
    helm.sh/chart: ingress-nginx-4.6.1
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: telus-ping-ingress
    app.kubernetes.io/version: "1.7.1"
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: controller
  name: telus-ping-ingress-ingress-nginx-controller-internal
  namespace: default
spec:
  type: "LoadBalancer"
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 1443
      protocol: TCP
      targetPort: 1443
    - name: ldap
      port: 1389
      protocol: TCP
      targetPort: 1389
    - name: ldaps
      port: 1636
      protocol: TCP
      targetPort: 1636
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: telus-ping-ingress
    app.kubernetes.io/component: controller