apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: likeminds
    app.kubernetes.io/name: pingfederate
  name: likeminds-pingfederate
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: likeminds
      app.kubernetes.io/name: pingfederate
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: likeminds
        app.kubernetes.io/name: pingfederate
        clusterIdentifier: likeminds-pingfederate
    spec:
      affinity: {}
      containers:
      - args: null
        envFrom:
        - configMapRef:
            name: likeminds-global-env-vars
            optional: true
        - configMapRef:
            name: likeminds-env-vars
            optional: true
        - configMapRef:
            name: likeminds-pingfederate-env-vars
        - secretRef:
            name: devops-secret
            optional: true
        - secretRef:
            name: likeminds-pingfederate-git-secret
            optional: true
        image: pingidentity/pingfederate:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /opt/liveness.sh
          failureThreshold: 4
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: pingfederate
        ports:
        - containerPort: 9031
          name: https
        - containerPort: 9999
          name: pfadmin
        readinessProbe:
          exec:
            command:
            - /opt/readiness.sh
          failureThreshold: 4
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 0
            memory: 1Gi
        startupProbe:
          exec:
            command:
            - /opt/liveness.sh
          failureThreshold: 90
          periodSeconds: 10
          timeoutSeconds: 5
      enableServiceLinks: true
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsUser: 9031
      shareProcessNamespace: false
      terminationGracePeriodSeconds: 30